services:
  website:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ".:/workspace"
    working_dir: /workspace
    command: ["bundle", "exec", "jekyll", "serve", "-s", "docs/", "-H", "0.0.0.0", "--livereload", "--drafts"]
